### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by calvaris** [alexanderwink/subdl#27]
I am experiencing:

```
$ subdl my_file_name.mkv
Traceback (most recent call last):
  File "/usr/local/bin/subdl", line 6, in <module>
    from subdl import cli
  File "/usr/local/lib/python2.7/dist-packages/subdl.py", line 196
    print("Searching for subtitles for moviehash=%s..." % (moviehash), file=sys.stderr)
                                                                           ^
SyntaxError: invalid syntax
```

I guess either I am missing anything or there is something wrong

**Comment by alexanderwink** [comment]
Please use python3
