### ISSUE TITLE
subdl --list-languages no longer works

### ISSUE THREAD

**Issue by PacoH** [alexanderwink/subdl#40]
```
subdl --version
subdl 1.1.2
```

```
subdl --list-languages
Traceback (most recent call last):
  File "/usr/local/bin/subdl", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/subdl.py", line 534, in cli
    main(sys.argv[1:])
  File "/usr/local/lib/python3.11/site-packages/subdl.py", line 459, in main
    files = parseargs(args)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/subdl.py", line 444, in parseargs
    ListLanguages()
  File "/usr/local/lib/python3.11/site-packages/subdl.py", line 358, in ListLanguages
    languages = xmlrpc_server.GetSubLanguages('')['data']
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'GetSubLanguages'
```

**Comment by b1337xyz** [comment]
Easy fix, put `osdb_connect()` before `files = parseargs(args)`

```diff
 def main(args):
-    files = parseargs(args)
     osdb_connect()
+    files = parseargs(args)
```

**Comment by alexanderwink** [comment]
This was unintentionally resolved in https://github.com/alexanderwink/subdl/pull/35
