### ISSUE TITLE
[v1.1.2] All subtitle queries throwing error 'KeyError: 'data'

### ISSUE THREAD

**Issue by Drag0nFly** [alexanderwink/subdl#43]
It appears recent Python versions have caused subdl to break. 

All subtitle queries are now throwing the following error:

```
Traceback (most recent call last):
  File "/usr/bin/subdl", line 537, in <module>
    cli()
  File "/usr/bin/subdl", line 534, in cli
    main(sys.argv[1:])
  File "/usr/bin/subdl", line 485, in main
    search_results = SearchSubtitlesByString(file_name, options.lang)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/subdl", line 227, in SearchSubtitlesByString
    data = results['data']
           ~~~~~~~^^^^^^^^
KeyError: 'data'
```

In addition to throwing (minor) warnings for escape sequences

```
/usr/bin/subdl:80: SyntaxWarning: invalid escape sequence '\.'
  'bitninja\.io',
/usr/bin/subdl:81: SyntaxWarning: invalid escape sequence '\.'
  'Please rate this subtitle at www\.osdb\.link',
/usr/bin/subdl:83: SyntaxWarning: invalid escape sequence '\.'
  'firebit\.org',
/usr/bin/subdl:84: SyntaxWarning: invalid escape sequence '\.'
  'humanguardians\.com',
/usr/bin/subdl:86: SyntaxWarning: invalid escape sequence '\.'
  'recast\.ai',
/usr/bin/subdl:207: SyntaxWarning: invalid escape sequence '\d'
  result = re.search("\d+", imdb_id)
subdl 1.1.2
```

**Comment by hejops** [comment]
This (most likely) has nothing to do with Python. See #42.

**Comment by commonsourcecs** [comment]
On the contrary, it would appear to be related to python changes. 

See for example here:
https://github.com/HandBrake/HandBrake/issues/5454

I propose making each of those 'real' strings, as seen with PR #44 

But this only tackles the second minor escape sequences error. 

It may be worth noting that earlier packaged versions, such as seen on Arch Linux, before 
https://github.com/alexanderwink/subdl/commit/e01c13eff070bf7dae6753c33c6698ce460075ad
was applied, only require that and do not suffer the same major breakage resulting in " KeyError: 'data' "
